_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "pretrained/r101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NUM_CLASSES: 3
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (2000, )
  MAX_ITER: 2500
  IMG_PER_BATCH_LABEL: 16
  BASE_LR: 0.01
DATASETS:
  TRAIN: ('UODD_5shot',)
  TEST: ('UODD_test',)
KD:
  BURN_UP_STEP: 1000
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.9996
  LOSS_WEIGHT: 4.0
OUTPUT_DIR: "checkpoints/UODD/5shot"